### ISSUE TITLE
Description of vector/tabular data?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/classification#10]
From #1: Can classification be used to describe a field in vector or tabular asset? If yes, how? We should provide an example then.

**Comment by pjhartzell** [comment]
How does the [label](https://github.com/stac-extensions/label) (and potential [vector-label](https://github.com/stac-extensions/vector-label) extension) fit into this, particularly for vector data?

**Comment by pjhartzell** [comment]
Is there a reason why `classification:classes` would be used rather than `label:classes`? It's taking me a bit to understand the `label` extension.

If there is an extension that handles vector data, would effort be better spent on refining that extension rather than mixing vector data into the classification extension? Or do we need a new way to describe vector data than currently done in the existing and/or proposed extensions?

**Comment by drwelby** [comment]
The more I look at the `label` extension the less I understand it. But since it doesn't seem to have anything that maps values to labels, I'm inclined to let someone who uses the label extension to integrate `classification:classes` if they want to.

For vector assets I think the `table` extension could work, and much like rasters can use bands that are classified, a vector asset could do the same with `table:column`.

**Comment by matthewhanson** [comment]
The label extension originally was for providing labels to vector regions for use as training data. It later expanded to include raster data as well. However, the current feeling among several people is that the label extension was too confusing and complicated and what was really needed was a classification extension that was only for raster data, as the two are quite a bit different and they would be used in completely different ways. 

Classified rasters will often be used directly alongside other raster data with the same pixel locations and sizes. Vector labels on the other hand are probably used with other arbitrary datasets in order to calculate statistics or to clip and use as training data.

My opinion is that the label extension should be updated to remove the raster bits entirely after this extension is published.

**Comment by pjhartzell** [comment]
Thanks, @matthewhanson. Any thoughts on using `classification:classes` in tabular data? Here is an example of the [table](https://github.com/stac-extensions/table) extension being used where the values in some of the columns are classes: https://planetarycomputer.microsoft.com/api/stac/v1/collections/us-census/items/2020-cb_2020_us_vtd_500k

For example, the state and county FIPS codes could be defined with `classification:classes`.

Or do we want to restrict the classification extension to raster data, hard stop?

**Comment by drwelby** [comment]
https://www.census.gov/library/reference/code-lists/route-type-codes.html is an example where it could be used on the vector/tabular side.

To support this use case we just need to insure the `values` allows strings, which at the moment it does.

**Comment by pjhartzell** [comment]
Is it reasonable to limit the initial release of the extension to raster data only? And only expand to other data types if there is community interest? Might be good to keep it simple to start with.

**Comment by drwelby** [comment]
It works for me to start out really specific and say:

- only for rasters
- values are only integers

which gets Planetary Computer Landsat and Maxar ARD rolling to start implementation.

Then consider:

- expanding values to strings in cooperation with `table` devs
- consider ranges, maybe a slightly different field like `classification:class-groups`

**Comment by pjhartzell** [comment]
That works for me. Looking forward to seeing this in use.

**Comment by m-mohr** [comment]
Uh, let me check what I need for CARD4L. The proposal might be good enough, but want to make sure it is. :-)

**Comment by drwelby** [comment]
No worries, we would wait for your final 👍 anyway!

**Comment by m-mohr** [comment]
I'm on PTO next week and won't get to it until then. Are you find with that? Otherwise, I guess you can request feedback from others already also... or what's the plan for the next weeks?

**Comment by drwelby** [comment]
I made an issue for a Road Map, the plan seems like we'll start with a tight core implementation to get Planetary Computer started as the pilot with Maxar ARD and Planet UDM following. We can then consider enhancements given real use cases that can pilot them.

Since there's a STAC Meetup on March 28th I'll probably shoot for that as the first announcement.

If there's a specific part in CARD4L you'd like me to look into while you're out, let me know.
