### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by pjhartzell** [stac-extensions/classification#42]
PR #35 is a breaking change. Would be nice to reference that with a versioned schema.

**Comment by gadomski** [comment]
Since #35 is breaking, doesn't it require a MAJOR version bump to 2.0.0?

**Comment by m-mohr** [comment]
How do we want to proceed with the release?

We have the following changes already in the changelog:

Added:
- `nodata` to `classification:classes`
- Regular expression to validate `name` is machine-readable

Changed:
- Allow CommonMark for the `description` fields.
- `name` is required rather than `description`

Fixed:
- Fixed tests which were validating against v1.0.0 instead of v1.1.0

Open Issues:
- https://github.com/stac-extensions/classification/issues/41 - This is a potential larification and could be added later. No change to the spec is expected IMHO.
- https://github.com/stac-extensions/classification/issues/38 - Potentially an additional rel type, also there might be one coming up for palettes. But I don't think we'd need to wait for them. We could also just open a slim PR for it, too.
- https://github.com/stac-extensions/classification/issues/33 - Larger question about whether we want to cater for ranges. We may also just close it? Maybe stick with the simpler approach we have...

Preferences? I'd like to move this forward, release and eventually update the maturity levels for this one, too :-)

**Comment by gadomski** [comment]
@pjhartzell and I were having a discussion about ranges the other day ... I'd like to resolve #33 before releasing, since a v2 would be a good chance to include ranges if we do decide to add them. I'll ask Preston to update #33 with our thoughts and examples.

**Comment by m-mohr** [comment]
I agree with @drwelby except if we get a solid proposal for ranges defined in the next couple of weeks.

**Comment by m-mohr** [comment]
Is it fine if I release the existing changes into a new version 2.0 in the next weeks?

**Comment by m-mohr** [comment]
Released
